#!/bin/bash

if [ "$EUID" -ne 0 ]
  then echo "Run script as root!"
  exit 0
fi

if [ -n "$1" ]; then
  FILE="$1"
  sameFile=$(ls /etc/bind/zones | grep "db.$FILE.robbe-jacobs1.sb.uclllabs.be")
  if [[ "$sameFile" == "db.$FILE" ]]; then
  	echo "A zone with this name already exists"
	exit 0
  fi

  touch $(echo "/etc/bind/zones/db.$FILE.robbe-jacobs1.sb.uclllabs.be")

  echo "\$TTL    4800
@       IN      SOA     ns.$FILE.robbe-jacobs1.sb.uclllabs.be. root.$FILE.robbe-jacobs1.sb.uclllabs.be. (
  		1	; Serial
 	   604800	; Refresh
	      600	; Retry
	      600	; Expire
           604800 )	; Negative Cache TTL
	   
@	IN	NS	ns.robbe-jacobs1.sb.uclllabs.be.
@	IN	NS	ns.$FILE.robbe-jacobs1.sb.uclllabs.be.

ns	IN	A	193.191.177.207
@	IN	A	193.191.177.207" > /etc/bind/zones/db.$FILE.robbe-jacobs1.sb.uclllabs.be


  echo "$1	IN	NS	ns.robbe-jacobs1.sb.uclllabs.be." >> /etc/bind/zones/db.robbe-jacobs1.sb.uclllabs.be

  echo "zone \"$FILE.robbe-jacobs1.sb.uclllabs.be\" {
	type master;
	file \"/etc/bind/zones/db.$FILE.robbe-jacobs1.sb.uclllabs.be\";
  };" >> /etc/bind/named.conf.mrt-zones

  serialline=$(grep "Serial" /etc/bind/zones/db.robbe-jacobs1.sb.uclllabs.be)
  serialnumber=$(echo $serialline | cut -d \; -f 1)
  ((serialnumber++))
  newserial="$serialnumber	; Serial"
  echo $newserial;
  sed -i "s/.*Serial.*/\t\t\t	$newserial/g" /etc/bind/zones/db.robbe-jacobs1.sb.uclllabs.be

  rndc reload
  systemctl restart bind9
else
  echo "no variables given"
  exit 0
fi	
