#!/bin/bash

if [ "$EUID" -ne 0 ];then
  echo "Not executed as root"
  exit 0
fi

if [ -n "$1" ]; then
	
  if [ "$1" == "-t" ]; then	
    if [ "$2" == "CNAME" ]; then
      FILE="/etc/bind/zones/db.`echo $4`"
      echo "$3	IN	CNAME	$4" >> $FILE
    elif [ "$2" == "A" ]; then
      FILE="/etc/bind/zones/db.`echo $5`"
      echo "$3	IN	A	$4" >> $FILE
    elif [ "$2" == "MX" ]; then
      FILE="/etc/bind/zones/db.`echo $5`"
      echo "@	IN	MX	10	$3.$5." >> $FILE
      echo "$3	IN	A	$4" >> $FILE
    fi
  else
    FILE="/etc/bind/zones/db.`echo $3`"
    echo "$1	IN	A	$2" >> $FILE
  fi
else
  echo "no variables given"
  exit 0
fi	
serialline=$(grep "Serial" "$FILE")
serialnumber=$(echo $serialline | cut -d \; -f 1)
((serialnumber++))
newserial="$serialnumber         ; Serial"
echo $newserial;
sed -i "s/.*Serial.*/\t\t\t     $newserial/g" "$FILE"

rndc reload
systemctl restart bind9
