#!/bin/bash

subdomain="`echo $1 | cut -d '.' -f1-2`"

compare="`echo $1 | cut -d '.' -f3-`"
filename="$subdomain"

if [ "$EUID" -ne 0 ];then
  echo "Not executed as root"
  exit 0
fi

if [  -n "$1" ]; then
  if [  -d "/var/www/html/$subdomain" ]; then
  	echo "Subdomain already exists";
	exit 0;
  fi

  if [ "$compare" != "robbe-jacobs1.sb.uclllabs.be" ]; then
	echo "Invalid domain";
  else
	sudo mkdir -p /var/www/html/$subdomain;
	touch /var/www/html/$subdomain/index.html;
	echo "welcome $subdomain" >> /var/www/html/$subdomain/index.html;

	touch /etc/apache2/sites-available/ignore.$filename.conf;
	echo "<VirtualHost *:80>
        # The ServerName directive sets the request scheme, hostname and port that
        # the server uses to identify itself. This is used when creating
        # redirection URLs. In the context of virtual hosts, the ServerName
        # specifies what hostname must appear in the request's Host: header to
        # match this virtual host. For the default virtual host (this file) this
        # value is not decisive as it is used as a last resort host regardless.
        # However, you must set it for any further virtual host explicitly.
        #ServerName www.example.com

        ServerAdmin webmaster@localhost
        ServerName $1
        ServerAlias www.$1

        DocumentRoot /var/www/html/$subdomain
        # Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
        # error, crit, alert, emerg.
        # It is also possible to configure the loglevel for particular
        # modules, e.g.
        #LogLevel info ssl:warn

        ErrorLog ${APACHE_LOG_DIR}/$subdomain.error.log
        CustomLog ${APACHE_LOG_DIR}/$subdomain.access.log combined

        # For most configuration files from conf-available/, which are
        # enabled or disabled at a global level, it is possible to
        # include a line for only one particular virtual host. For example the
        # following line enables the CGI configuration for this host only
        # after it has been globally disabled with "a2disconf".
        #Include conf-available/serve-cgi-bin.conf
</VirtualHost>" >> /etc/apache2/sites-available/ignore.$filename.conf;

	sudo a2ensite ignore.$filename.conf

	sudo dns_add_record -t A $subdomain 193.191.177.207 robbe-jacobs1.sb.uclllabs.be

	sudo systemctl restart bind9
	sudo systemctl restart apache2
  fi
else
	echo "No variables given"
fi
